# Generated by Django 4.2.2 on 2023-09-10 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('birthday', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='chocolate_received',
            new_name='chocolate_received',
        ),
    ]
