# Generated by Django 4.2.2 on 2023-09-29 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('kitchen', '0005_alter_dish_options_alter_dish_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('dishes', models.ManyToManyField(to='kitchen.dish')),
            ],
        ),
    ]
