# Generated by Django 4.2.2 on 2023-09-07 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bibliouser',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='avatars/'),
        ),
        migrations.AlterField(
            model_name='bibliouser',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=15),
        ),
    ]
