# Generated by Django 4.2.2 on 2023-09-18 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_bibliouser_avatar_alter_bibliouser_phone'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliouser',
            options={'permissions': (('can_rent', ' Can rent a book'),)},
        ),
    ]
