# Generated by Django 4.2.2 on 2023-09-18 19:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_bibliouser_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bibliouser',
            options={'verbose_name': 'user', 'verbose_name_plural': 'users'},
        ),
    ]
