# Generated by Django 4.2.2 on 2023-09-04 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0002_bookcategory_bookedition_remove_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookedition',
            name='isbn',
            field=models.CharField(blank=True, max_length=17),
        ),
    ]
