# Generated by Django 4.2.2 on 2023-09-04 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shelf', '0003_alter_bookedition_isbn'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'ordering': ('last_name', 'first_name'), 'verbose_name_plural': 'Authors'},
        ),
    ]
