# Generated by Django 4.2.10 on 2024-02-17 21:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_remove_weatherappuser_settings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weathersettings',
            old_name='rain',
            new_name='wind',
        ),
    ]
