# Generated by Django 4.2.2 on 2023-07-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_comment_bid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='auction',
            name='image_link',
            field=models.CharField(default='https://cdn.pixabay.com/photo/2021/07/20/12/35/auction-6480582_1280.jpg', max_length=254),
        ),
    ]
