# Generated by Django 4.2.2 on 2023-07-05 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_alter_auction_description_alter_auction_image_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_link',
            field=models.ImageField(default='https://cdn.pixabay.com/photo/2021/07/20/12/35/auction-6480582_1280.jpg', upload_to='images/auctions/'),
        ),
    ]
