# Generated by Django 4.2.2 on 2023-07-05 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_image_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='image_link',
        ),
        migrations.AddField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='images/auctions/'),
        ),
    ]
