# Generated by Django 4.2.2 on 2023-07-05 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_auction_image_link_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default='images/auctions/default.jpg', upload_to='images/auctions/'),
        ),
    ]
