# Generated by Django 4.2.2 on 2023-07-05 22:20

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_auction_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image',
            field=models.ImageField(default=auctions.models.get_default_image_path, upload_to='images/auctions/'),
        ),
    ]
