# Generated by Django 4.2.2 on 2023-07-06 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0010_auction_creator_watchlist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='creator',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auctionCreator', to=settings.AUTH_USER_MODEL),
        ),
    ]
