# Generated by Django 4.2.2 on 2023-07-06 15:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0011_alter_auction_creator'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='auction',
            name='creator',
        ),
        migrations.AddField(
            model_name='auction',
            name='author',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='auctionAutor', to=settings.AUTH_USER_MODEL),
        ),
    ]
