# Generated by Django 4.2.2 on 2023-07-06 15:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_remove_watchlist_auction_remove_watchlist_user_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='interested_user',
            new_name='user',
        ),
    ]
