# Generated by Django 4.2.2 on 2023-07-06 16:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_rename_interested_user_watchlist_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='WatchList',
        ),
    ]
