# Generated by Django 4.2.2 on 2023-07-06 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0016_watchlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='watchlist',
            name='offer',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='offer',
            field=models.ManyToManyField(related_name='watchlists', to='auctions.auction'),
        ),
    ]
