# Generated by Django 4.2.2 on 2023-07-07 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0017_remove_watchlist_offer_watchlist_offer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='starting_bid',
            new_name='current_bid',
        ),
    ]
