# Generated by Django 4.2.2 on 2023-07-12 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0022_auction_confirmed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=15),
        ),
    ]
