# Generated by Django 4.2.2 on 2023-08-29 09:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_remove_post_like_count'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='user',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='text',
            new_name='content',
        ),
    ]
