# Generated by Django 4.2.2 on 2023-10-01 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_rename_new_orders_user_new_items_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='new_items',
            new_name='new_orders',
        ),
    ]
