# Generated by Django 4.2.2 on 2023-10-02 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_remove_order_dishes_orderitem'),
        ('users', '0007_remove_user_orders_user_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='orders',
            field=models.ManyToManyField(related_name='user', to='orders.order'),
        ),
    ]
