# Generated by Django 4.2.2 on 2023-09-28 21:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0003_alter_dish_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='dish',
            name='price',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='ingredient',
            name='amount',
            field=models.FloatField(),
        ),
    ]
