# Generated by Django 4.2.2 on 2023-09-28 21:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kitchen', '0004_dish_price_alter_ingredient_amount'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dish',
            options={'verbose_name_plural': 'Dishes'},
        ),
        migrations.AlterField(
            model_name='dish',
            name='price',
            field=models.FloatField(),
        ),
    ]
